// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetsDog.Data;

#nullable disable

namespace PetsDog.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PetsDog.Models.Agendamento", b =>
                {
                    b.Property<int>("id_agendamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_agendamento"));

                    b.Property<int?>("Profissionalid_profissional")
                        .HasColumnType("int");

                    b.Property<int?>("ServicoIdservico")
                        .HasColumnType("int");

                    b.Property<DateTime>("data_hora")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("id_animal")
                        .HasColumnType("int");

                    b.Property<int>("id_profissional")
                        .HasColumnType("int");

                    b.Property<int>("id_servico")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .HasColumnType("longtext");

                    b.HasKey("id_agendamento");

                    b.HasIndex("Profissionalid_profissional");

                    b.HasIndex("ServicoIdservico");

                    b.HasIndex("id_animal");

                    b.HasIndex("id_profissional");

                    b.HasIndex("id_servico");

                    b.ToTable("Agendamento");
                });

            modelBuilder.Entity("PetsDog.Models.Animal", b =>
                {
                    b.Property<int>("id_animal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_animal"));

                    b.Property<string>("Especie")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_cliente")
                        .HasColumnType("int");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Porte")
                        .HasColumnType("longtext");

                    b.HasKey("id_animal");

                    b.HasIndex("Id_cliente");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("PetsDog.Models.Cliente", b =>
                {
                    b.Property<int>("Idcliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Idcliente"));

                    b.Property<DateTime>("Datacadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.HasKey("Idcliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("PetsDog.Models.Profissional", b =>
                {
                    b.Property<int>("id_profissional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_profissional"));

                    b.Property<string>("DiponibilidadeFim")
                        .HasColumnType("longtext");

                    b.Property<string>("DisponibilidadeInicio")
                        .HasColumnType("longtext");

                    b.Property<string>("especialidade")
                        .HasColumnType("longtext");

                    b.Property<string>("nome")
                        .HasColumnType("longtext");

                    b.HasKey("id_profissional");

                    b.ToTable("Profissionais");
                });

            modelBuilder.Entity("PetsDog.Models.Servico", b =>
                {
                    b.Property<int>("Idservico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Idservico"));

                    b.Property<int>("duracao_min")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .HasColumnType("longtext");

                    b.Property<decimal>("preco")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Idservico");

                    b.ToTable("Servicos");
                });

            modelBuilder.Entity("PetsDog.Models.Agendamento", b =>
                {
                    b.HasOne("PetsDog.Models.Profissional", null)
                        .WithMany("Agendamentos")
                        .HasForeignKey("Profissionalid_profissional");

                    b.HasOne("PetsDog.Models.Servico", null)
                        .WithMany("Agendamentos")
                        .HasForeignKey("ServicoIdservico");

                    b.HasOne("PetsDog.Models.Animal", "Animal")
                        .WithMany("Agendamentos")
                        .HasForeignKey("id_animal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetsDog.Models.Profissional", "Profissional")
                        .WithMany()
                        .HasForeignKey("id_profissional")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetsDog.Models.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("id_servico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Profissional");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("PetsDog.Models.Animal", b =>
                {
                    b.HasOne("PetsDog.Models.Cliente", "Cliente")
                        .WithMany("Animals")
                        .HasForeignKey("Id_cliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("PetsDog.Models.Animal", b =>
                {
                    b.Navigation("Agendamentos");
                });

            modelBuilder.Entity("PetsDog.Models.Cliente", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("PetsDog.Models.Profissional", b =>
                {
                    b.Navigation("Agendamentos");
                });

            modelBuilder.Entity("PetsDog.Models.Servico", b =>
                {
                    b.Navigation("Agendamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
